# docker-compose.yml (Versión más limpia)
version: '3.8'
 
services:
  servidor:
    build: ./servidor
    environment:
      # --- Variables que SÍ dejamos ---
      DATABASE_URL: mongodb://mongo:27017/liga_docker # Necesaria para conectar con Mongo dentro de Docker
      PORT: 4000 # El puerto interno del servidor Node

      # --- Variables que quitamos (se definirán en .env) ---
      # FRONTEND_URL: http://localhost:8081 # <-- QUITADA (depende del entorno)
      # TOKEN_SECRET: "TU_SECRETO_JWT_AQUI" # <-- QUITADA (es un secreto)
      # Añade aquí cualquier OTRA variable que sea específica del entorno o secreta
    depends_on:
      - mongo
    networks:
      - app-network
    volumes:
      #- ./servidor:/app
      - /app/node_modules
 
  cliente:
    build:
      context: ./cliente
      dockerfile: Dockerfile
      args:
        # --- CORREGIDO ---
        # Pasa la URL completa del backend dentro de la red Docker
        VITE_API_BASE_URL_ARG: /api/
        # Pasa el origen completo del backend para las imágenes
        VITE_BACKEND_IMAGE_ORIGIN_ARG: ""
        # --- FIN CORRECCIÓN ---
    ports:
      - "8090:80"
    depends_on:
      - servidor
    networks:
      - app-network

  mongo:
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    ports:
      - "27017:27017"

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
