
services:
  servidor:
    build: ./servidor
    ports:
      - "4000:4000"
    environment:
      # Variables de runtime para el backend (conexión a DB, etc.)
      DATABASE_URL: mongodb://mongo:27017/liga_docker
      # ---> AGREGA ESTA LÍNEA <---
      # Reemplaza <IP_DE_TU_OMV> con la IP real de tu servidor OMV
      FRONTEND_URL: http://192.168.1.250:8081
      # Otras variables como JWT_SECRET, etc. si las tienes
    depends_on:
      - mongo
    networks:
      - app-network
    volumes:
      - ./servidor:/app # Opcional para desarrollo, quitar en producción pura
      - /app/node_modules # Para evitar sobreescribir node_modules

  cliente:
    build:
      context: ./cliente # Directorio donde está el Dockerfile del cliente
      dockerfile: Dockerfile # Nombre del Dockerfile (usualmente Dockerfile)
      # ---> PASO 3: Pasa el argumento de construcción aquí <---
      args:
        # El nombre aquí debe coincidir con el ARG en el Dockerfile
        - VITE_API_BASE_URL_ARG=/api
    ports:
      - "8081:80" # O el puerto que quieras exponer, ej 8080:80
    depends_on:
      - servidor
    networks:
      - app-network
    # No necesitas 'volumes' para el cliente en producción,
    # ya que Nginx sirve los archivos copiados durante el build.

  mongo:
    image: mongo:4.4  
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    ports: 
      - "27017:27017"

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
